services:
  ecommerce-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=EnterpriseDbPass123!
    ports:
      - "5433:5432"
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data

  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=ecommerce-db;Port=5432;Database=ecommerce_db;Username=postgres;Password=EnterpriseDbPass123!
    depends_on:
      - ecommerce-db

volumes:
  ecommerce-db-data:
